version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 22
        - nvm use 22
        - node --version
        - npm install
    build:
      commands:
        - ./scripts/build.sh
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - '**/*'
