version: 1
env:
  variables:
    SECRET_NAME: qbusiness-config-qbusiness-public-sector-090df5a0
    AWS_REGION: us-east-1
    SESSION_DURATION_MINUTES: 15
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 22
        - nvm use 22
        - node --version
        - npm install
    build:
      commands:
        - ./scripts/build.sh
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - '**/*'
